%%% Compute the target contribution in each 128 x 128 cell generated by the simulation.
%%% Process: For each cell, generate the simulated mWidar signal. Look a window around where the target is an multiply the signal intensity in each cell in that window
%%% Result: A 128 x 128 lookup table of likely target intensities for targets in those cells.
%%% Things to look at after the result: Variance in signal intensities, size of window (defualt 5)

addpath('TBD/Includes')

s = simulator();
p_window = 5; %%% Define the size of the square window we are looking at

L = zeros(128,128); % Store like in here

for i = 1:128 % rows

    pRowStart = max(1,i - p_window);
    pRowEnd = min(128, i + p_window); 
    i
    for j = 1:128 % cols
        
        pos = {[i, j]};
        % Generate the signal
        signal = s.generate_mWidar_image(pos, 'pixels', true);

        % Sliding window:
        pColStart = max(1,i - p_window);
        pColEnd = min(128, i + p_window);

        pRows = pRowStart:1:pRowEnd;
        pCols = pColStart:1:pColEnd;

        score = 1;
        % more loops
        for k = 1:size(pRows,2)
            for n = 1:size(pCols,2)
                score = score*signal(k,n);
            end
        end
        L(i,j) = score;
    end
end

save('TBD/supp/TargetContribution.mat', "L")
var(L(:))